### ISSUE TITLE
JOSS review feedback

### ISSUE THREAD

**Issue by luizirber** [kdmurray91/libqcpp#3]
Hi!

While reviewing  https://github.com/openjournals/joss-reviews/issues/232 I missed some things:

- `Example usage` and `functionality`: an example (maybe using the test data you already have available?) helps on checking how the software works, also because the `trimit` help and [docs](http://qcpp.readthedocs.io/en/latest/applications.html#trimit) are a bit sparse.
- `Community guidelines`: you can add CONTRIBUTING.md to the repo, or expand the developer section of the docs

Nice API docs and library, BTW!

# Tasks

- [x] Contributing.md
- [x] Tutorial documentation

**Comment by kdmurray91** [comment]
@luizirber Thanks heaps for the review. I'm at a conference next week, but will do my best to have a small example & some tutorial-style docs prepared within a week. I'll put a contributing.md up too.

**Comment by kdm9** [comment]
Hi @luizirber, I think I have addressed your concerns. The online docs at qcpp.rtfd.io now contain a tutorial, and `CONTRIBUTING.md` now exists.
